name: Deploy Hugo site to Pages

on:
  # Trigger on push to the main branch
  push:
    branches: ["main"]

  # Trigger manually from the Actions tab
  workflow_dispatch:

# Permissions to deploy to GitHub Pages
permissions:
  contents: read
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Hugo CLI
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Build the site
      - name: Build site
        run: hugo --minify

      # Upload the public folder to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  deploy:
    # Deploy the artifact uploaded in the build job to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
